// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PermDnamics_Toshmatov.Models;

namespace PermDnamics_Toshmatov.Migrations
{
    [DbContext(typeof(ChartContext))]
    [Migration("20260406064321_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.27");

            modelBuilder.Entity("PermDnamics_Toshmatov.Models.ChartSave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SaveDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChartSaves");
                });
#pragma warning restore 612, 618
        }
    }
}
